[package]
name = "rsrv_click"
version = "0.1.0"
edition = "2021"

[dependencies]
mouse-rs = "0.4.2"
chrono = "0.4.38"
rsntp = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"